import os
from datetime import datetime
import pytz

# 한국 시간 설정
KST = pytz.timezone('Asia/Seoul')
CURRENT_TIME = datetime.now(KST).strftime("%Y-%m-%d %H:%M:%S (KST)")

# 통합 데이터 소스
DATA_SOURCES = {
    "📢 공식 채널 (Official)": [
        {"name": "공식 트위터 (글로벌)", "url": "https://twitter.com/PokemonGoApp"},
        {"name": "공식 트위터 (한국)", "url": "https://twitter.com/PokemonGOAppKR"},
        {"name": "공식 블로그 (뉴스)", "url": "https://pokemongolive.com/post/"},
    ],
    "⚡ 속보 및 데이터 (Intel)": [
        {"name": "LeekDuck (이벤트 일정)", "url": "https://leekduck.com/"},
        {"name": "The Silph Road (연구 데이터)", "url": "https://thesilphroad.com/"},
        {"name": "Pokémon GO Hub (종합 뉴스)", "url": "https://pokemongohub.net/"},
        {"name": "GO Stadium (PvP 랭킹)", "url": "https://gobattlelog.com/"},
    ],
    "📺 필수 유튜브 채널 (Influencers)": [
        {"name": "쌈 (Ssam) - 한국 공략", "url": "https://www.youtube.com/@ssampogotv"},
        {"name": "쟁구 (Jaenggu) - 뉴스/티어", "url": "https://www.youtube.com/@jaenggu"},
        {"name": "Trainer Tips (심층 분석)", "url": "https://www.youtube.com/c/TrainerTips"},
        {"name": "BrandonTan91 (하드코어)", "url": "https://www.youtube.com/c/BrandonTan91"},
        {"name": "ZyoniK (PvP 전문)", "url": "https://www.youtube.com/c/ZyoniK"},
    ],
    "📚 도감 및 DB (All Pokémon Database)": [
        {"name": "🇰🇷 한국 공식 포켓몬 도감 (일러스트)", "url": "https://www.pokemonkorea.co.kr/pokedex"},
        {"name": "📊 GO Hub 스탯 DB (CP/공격값)", "url": "https://db.pokemongohub.net/"},
        {"name": "✨ 이로치(Shiny) 모습 체크리스트", "url": "https://leekduck.com/shiny/"},
        {"name": "📖 나무위키 포켓몬고 도감 (실전 팁)", "url": "https://namu.wiki/w/Pokémon%20GO/%ED%8F%AC%EC%BC%93%EB%AA%AC%20%EB%8F%84%EA%B0%90"},
    ]
}

def generate_markdown():
    md_content = f"# 📱 Pokémon GO Daily Ops Dashboard\n"
    md_content += f"**Updated:** {CURRENT_TIME}\n\n"
    md_content += "> Grand-Ops-Master님을 위한 일일 포켓몬고 브리핑 대시보드입니다.\n\n"

    for category, sites in DATA_SOURCES.items():
        md_content += f"## {category}\n"
        md_content += "| 소스 이름 | 바로가기 |\n"
        md_content += "| --- | --- |\n"
        for site in sites:
            md_content += f"| **{site['name']}** | [Link]({site['url']}) |\n"
        md_content += "\n"
    
    md_content += "---\n"
    md_content += "*Generated by GitHub Actions for Grand-Ops-Master*"
    
    return md_content

if __name__ == "__main__":
    report = generate_markdown()
    
    # 파일로 저장
    with open("POGO_DAILY_BRIEF.md", "w", encoding="utf-8") as f:
        f.write(report)
    
    print("✅ Dashboard generated successfully with Pokedex links.")
