import sqlite3
import os
import datetime
import requests
import psutil
import feedparser # RSS 파싱
import pandas as pd
from sklearn.ensemble import IsolationForest

# 설정
DB_PATH = os.getenv('DB_PATH', 'data/grand_ops_master.db')
DASH_PATH = os.getenv('DASHBOARD_FILE', 'data/omni_dashboard.md')

class NewsAggregator:
    """IT 및 AI 관련 뉴스 수집기"""
    def __init__(self):
        # 공신력 있는 테크 뉴스 RSS 피드 목록
        self.feeds = [
            "https://techcrunch.com/category/artificial-intelligence/feed/", # TechCrunch AI
            "https://www.wired.com/feed/category/science/latest/rss", # Wired Science/AI
            "https://feeds.feedburner.com/TheHackersNews", # Security
            "https://openai.com/blog/rss.xml" # OpenAI Blog
        ]
        self.keywords = ['AI', 'GPT', 'LLM', 'Generative', 'Nvidia', 'Data', 'Cyber', 'Cloud', 'Python', 'Model']

    def fetch_news(self, limit=5):
        news_items = []
        try:
            for url in self.feeds:
                feed = feedparser.parse(url)
                for entry in feed.entries[:5]: # 각 피드당 최신 5개 스캔
                    title = entry.title
                    link = entry.link
                    # 날짜 처리 (없으면 현재 시간)
                    published = getattr(entry, 'published', datetime.datetime.now().strftime('%Y-%m-%d'))[:10]
                    
                    # 키워드 필터링 (관심 주제만)
                    # 제목에 키워드가 있거나, AI 전용 피드인 경우
                    if any(k.lower() in title.lower() for k in self.keywords) or "artificial-intelligence" in url:
                        news_items.append({'date': published, 'source': feed.feed.title, 'title': title, 'link': link})
        except Exception as e:
            print(f"⚠️ News Fetch Error: {e}")
            return []

        # 날짜순 정렬 후 상위 N개 반환
        news_items.sort(key=lambda x: x['date'], reverse=True)
        return news_items[:limit]

class SystemMonitor:
    @staticmethod
    def get_metrics():
        return psutil.cpu_percent(interval=1), psutil.virtual_memory().percent, psutil.disk_usage('/').percent

    @staticmethod
    def get_geo_info():
        try:
            r = requests.get('https://ipinfo.io/json', timeout=3).json()
            return r.get('ip', 'Unknown'), r.get('city', 'Unknown'), r.get('country', 'Unknown')
        except: return "127.0.0.1", "Localhost", "N/A"

class ExternalFetcher:
    @staticmethod
    def get_bitcoin():
        try:
            r = requests.get("https://api.coingecko.com/api/v3/simple/price?ids=bitcoin&vs_currencies=usd", headers={'User-Agent': 'Bot'}, timeout=3)
            return r.json()['bitcoin']['usd']
        except: return 97500.0

class DashboardGenerator:
    def __init__(self, conn):
        self.conn = conn

    def draw_gauge(self, val):
        fill = int((val / 100) * 10)
        return "█" * fill + "░" * (10 - fill)

    def generate(self, sys, geo, btc, news_list):
        cpu, ram, disk = sys
        ip, city, country = geo
        
        with open(DASH_PATH, 'w', encoding='utf-8') as f:
            f.write(f"# 📰 Grand Ops News-Commander\n")
            f.write(f"> **Report Time:** {datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')} (KST) | **Location:** {city}, {country}\n\n")

            # 1. 시스템 모니터링 섹션
            f.write("### 🖥️ System & Resource Status\n")
            f.write(f"| Metric | Usage | Gauge | Status |\n|---|---|---|---|\n")
            f.write(f"| **CPU** | {cpu}% | `{self.draw_gauge(cpu)}` | {'🟢 Optimal' if cpu < 70 else '🔴 High'} |\n")
            f.write(f"| **RAM** | {ram}% | `{self.draw_gauge(ram)}` | {'🟢 Good' if ram < 80 else '🟡 Warning'} |\n")
            f.write(f"| **BTC** | ${btc:,.2f} | - | Global Index |\n\n")

            # 2. [NEW] AI & IT 뉴스 섹션
            f.write("### 🤖 Global AI & IT Trends (Live Briefing)\n")
            if news_list:
                f.write(f"| Date | Source | Headline (Click to Read) |\n|---|---|---|\n")
                for n in news_list:
                    # 소스명 간소화
                    src = n['source'].replace('TechCrunch', 'TC').replace('The Hacker News', 'HackerNews').split(' ')[0]
                    f.write(f"| {n['date']} | **{src}** | [{n['title']}]({n['link']}) |\n")
            else:
                f.write("> 📭 No major AI updates in the last hour.\n")
            
            f.write("\n---\n*Dashboard generated by Grand Ops AI Engine v23.0*")

def main():
    if not os.path.exists("data"): os.makedirs("data")
    conn = sqlite3.connect(DB_PATH)
    
    # 모듈 실행
    sys_mon = SystemMonitor()
    metrics = sys_mon.get_metrics()
    geo = sys_mon.get_geo_info()
    
    ext = ExternalFetcher()
    btc = ext.get_bitcoin()
    
    # 뉴스 수집
    print("📡 Scanning Global Tech News...")
    aggregator = NewsAggregator()
    news = aggregator.fetch_news(limit=7) # 상위 7개 뉴스
    
    # 대시보드 생성
    dash = DashboardGenerator(conn)
    dash.generate(metrics, geo, btc, news)
    
    conn.close()
    print("✅ Dashboard with News Generated.")

if __name__ == "__main__":
    main()
